language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t appetite_server .

before_script:
  - pip install -r src/requirements.txt
  - pip install coverage
  - pip install coveralls

script:
  - python tests/test.py
  - coverage run tests/test.py

after_success:
  coveralls